name: add-pool
description: Add your Pool to term-pool.org
title: "[add-pool]: "
labels: ["new-request"]
assignees:
  - dodopontocom
body:
  - type: markdown
    attributes:
      value: |
        Here you can request to add your pool to term-pool.org!
  - type: input
    id: pool_bech32
    attributes:
      label: ">>pool_bech32_id<<"
      description: IF your pool is activated, it will be add to term-pool.org soon, then visit term-pool.org/<TICKER> to check it out!
      placeholder: ex. pool1xzfrmeux886ckdm2ekk3t3xe2ch5666m7zxa6dt0zrfm5mq2ksm
    validations:
      required: true
  - type: dropdown
    id: alliances
    attributes:
      label: ">>cardano_alliances<<"
      description: Are you part of any these Cardano alliances?"
      multiple: true
      options:
        - xSPA
        - SSPA
        - ARMADA
        - Other
