name: Verify Pool

on:
  issues:
    types: [opened]

jobs:
  term-pool:
    runs-on: ubuntu-latest
    steps:
      - name: 'Pool status'
        env:
          BODY: ${{ github.event.issue.body }}
        run: |
          echo ${BODY} | grep -o 'pool1\S*'
          curl -sS -X POST "https://api.koios.rest/api/v0/pool_info" \
          -H "Content-Type: application/json" \
          -d '{"_pool_bech32_ids":[$(echo '${BODY}' | grep -o 'pool1\S*')]}' \
          | jq -r '.[].pool_status'
