name: Verify Pool

on:
  issues:
    types: [opened]

jobs:
  term-pool:
    runs-on: ubuntu-latest
    steps:
      - id: status
        name: 'Pool status'
        env:
          BODY: ${{ github.event.issue.body }}
          WHO: ${{ github.event.issue.actor }}
        run: |
          echo ${WHO}
          if [[ $(pool_id=$(echo ${BODY} | grep -o 'pool1\S*')
          curl -sS -X POST "https://api.koios.rest/api/v0/pool_info" \
          -H "Content-Type: application/json" \
          -d '{"_pool_bech32_ids":["'${pool_id}'"]}' \
          | jq -r '.[].pool_status') == "registered" ]]; then
            echo "pool is registered"
            else
              echo "pool is not registered"
              exit -1 || true
          fi
      
      - id: close
        name: 'Close issue'
        uses: peter-evans/close-issue@v2
        if: steps.status.conclusion == 'success'
        with:
          comment: Auto-closing issue with success
          labels: |
            pool_added
            
      - id: close_error
        name: 'Close issue as not implemented'
        uses: peter-evans/close-issue@v2
        if: steps.status.conclusion == 'failure'
        with:
          close-reason: not_planned
          comment: Auto-closing issue (probably pool not found nor registered)
          labels: |
            pool_not_added
      
    
