name: Verify Pool

on:
  issues:
    types: [opened, reopened]

jobs:
  issue-to-json:
    runs-on: ubuntu-latest
    name: Convert issue body to json
    outputs:
      payload-parsed: ${{ steps.payload.outputs.json_var }}
    steps:
      - name: Run parser
        id: parse
        uses: peter-murray/issue-forms-body-parser@v2.0.0
        with:
          issue_id: ${{ github.event.issue.number }}
          separator: '###'
          label_marker_start: '>>'
          label_marker_end: '<<'
      - name: Set Output
        id: payload
        run: echo json_var='${{ steps.parse.outputs.parse }}'
      - name: Print
        run: echo "${{ toJson(steps.payload.outputs.json_var) }}"

  term-pool:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          ref: 'infrastructure'
      - id: status
        name: 'Pool status'
        continue-on-error: true
        env:
          BODY: ${{ github.event.issue.body }}
        run: |
          pool_id=$(echo ${BODY} | grep -o 'pool1\S*')
          if [[ ! $(cat pool.csv | grep ${pool_id}) ]]; then
            if [[ $(curl -sS -X POST "https://api.koios.rest/api/v0/pool_info" \
              -H "Content-Type: application/json" \
              -d '{"_pool_bech32_ids":["'${pool_id}'"]}' \
              | jq -r '.[].pool_status') == "registered" ]]; then
              echo "pool is registered"
              ticker=$(curl -sS -X POST "https://api.koios.rest/api/v0/pool_info" \
              -H "Content-Type: application/json" \
              -d '{"_pool_bech32_ids":["'${pool_id}'"]}' \
              | jq -r '.[].meta_json.ticker')
              echo $(echo ${BODY} | grep -o 'pool1\S*'),${ticker} >> pool.csv
              else
                echo "pool is not registered on Cardano mainnet"
                exit -1
            fi
            else
                echo "pool is already added"
                exit -1
          fi
      - name: "commit"
        uses: EndBug/add-and-commit@v9
        with:
          message: add new pool
          committer_name: GitHub Actions
          committer_email: actions@github.com
      
      - id: close
        name: 'Close issue'
        uses: peter-evans/close-issue@v2
        if: steps.status.outcome == 'success'
        with:
          comment: Poll added. Verify - https://github.com/dodopontocom/yacp/blob/infrastructure/pool.csv
          labels: |
            pool_added
            
      - id: close_error
        name: 'Close issue as not implemented'
        uses: peter-evans/close-issue@v2
        if: steps.status.outcome != 'success'
        with:
          close-reason: not_planned
          comment: Probably pool not found nor registered. Maybe api was unavailable, please try later again
          labels: |
            pool_not_added